[development]
address = "localhost"
port = 8000
tls = { certs = "keys/devcert.pem", key = "keys/devkey.pem" }

# Change Me.
[production]
address = "0.0.0.0"
port = 8000
tls = { certs = "keys/devcert.pem", key = "keys/devkey.pem" }